# Generated by Django 2.2.6 on 2020-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userwork', models.CharField(max_length=55)),
                ('textabtwork', models.TextField()),
                ('listofwork', models.CharField(max_length=30)),
            ],
        ),
    ]
