# Generated by Django 2.0 on 2020-04-17 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='dd_choice',
            field=models.CharField(choices=[('Default', 'Default'), ('Personal', 'Personal'), ('Family', 'Family'), ('Office', 'Office')], default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
